const PACK_ADDRESS = import.meta.env.VITE_PACK_ADDRESS;
const CARD_ADDRESS = import.meta.env.VITE_CARD_ADDRESS;
const MARKETPLACE_ADDRESS = import.meta.env.VITE_MARKETPLACE_ADDRESS;
const CLIENT_ID = import.meta.env.VITE_CLIENT_ID;

export { PACK_ADDRESS, CARD_ADDRESS, MARKETPLACE_ADDRESS, CLIENT_ID };
